require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance
AllCops:
  TargetRubyVersion: '2.7'
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'bin/**/*'
    - 'lib/**/*'
    - 'vendor/**/*'
    - 'Rakefile'
    - '**/*.erb'
    - 'node_modules/**/*'
Style/FrozenStringLiteralComment:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/Documentation:
  Enabled: false
Layout/LineLength:
  # Ignore comments at beginning of files for model annotations
  IgnoredPatterns: ['\A#']
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Naming/PredicateName:
  Exclude:
    - 'app/graphql/types/**'
Metrics/BlockLength:
  Exclude:
    - '**/*.rake'
    - 'spec/**/*.rb'
Metrics/ClassLength:
  Enabled: false
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
Style/MethodCallWithArgsParentheses:
  Enabled: true
  Exclude:
    - 'spec/**/*.rb'
RSpec/Focus:
  Severity: error
RSpec/MultipleExpectations:
  Max: 2
Rails/EnumHash:
  Enabled: false